const enKeys = {
    "`" : "~",
    "1" : "!",
    "2" : "@",
    "3" : "#",
    "4" : "$",
    "5" : "%",
    "6" : "^",
    "7" : "&",
    "8" : "*",
    "9" : "(",
    "0" : ")",
    "-" : "_",
    "=" : "+",
    "backspace" : "backspace",

    "tab" : "tab",
    "q" : "!",
    "w" : "!",
    "e" : "!",
    "r" : "!",
    "t" : "!",
    "y" : "!",
    "u" : "!",
    "i" : "!",
    "o" : "!",
    "p" : "!",
    "[" : "!",
    "]" : "!",
    "\\" : "!",
    
    "caps Lock" : "caps Lock",
    "a" : "A",
    "d" : "D",
    "f" : "F",
    "g" : "G",
    "h" : "H",
    "j" : "J",
    "k" : "K",
    "l" : "L",
    ";" : ":",
    "'" : "\"",
    "enter" : "enter",
    
    "shift" : "shift",
    "z" : "shift",
    "x" : "L",
    "c" : "L",
    "v" : "L",
    "b" : "L",
    "n" : "L",
    "m" : "L",
    "," : "L",
    "." : "L",
    "/" : "L",
    "up" : "up",
    
    "ctrl" : "ctrl",
    "en" : "en",
    "space" : "space",
    "left" : "left",
    "down" : "down",
    "right" : "right",

    
    


}
export default enKeys;
